baseURL: https://fthdgn.com
theme: PaperMod
title: Fatih Doğan
author: Fatih Doğan
languageCode: tr-TR
enableRobotsTXT: true
disqusShortname: fatihdgn
disableKinds:
  - taxonomy
ignoreErrors:
  - error-disable-taxonomy
DefaultContentLanguage: tr
menu:
  main:
    - identifier: projects
      name: Projects
      url: /projects/
      weight: 10
permalinks:
  blog: /blog/:slug/
  tags: /tags/:slug
  videos: /videos/:slug
languages:
  tr:
    menu:
      main:
        - identifier: projects
          name: Projeler
          url: /projects/
          weight: 10
    weight: 1
  en:
    menu:
      main:
        - identifier: projects
          name: Projects
          url: /projects/
          weight: 10
    weight: 2
    params:
      description: Programming and some other stuff
      homeInfoParams:
        Title: Hi, I'm Fatih 👋
        Content: I'm trying to share my thoughts and actions here occasionally.
params:
  assets:
    disableFingerprinting: true
  env: production
  description: Programlama ve bazı şeyler
  favicon: images/favicon.png
  images:
    - images/share.png
  title: Fatih Doğan
  ShowShareButtons: true
  ShowReadingTime: true
  ShowCodeCopyButtons: true
  comments: true
  homeInfoParams:
        Title: Merhaba, ben Fatih 👋
        Content: Düşüncelerimi ve yaptıklarımı arada bir de olsa burada paylaşmaya çalışıyorum.
  socialIcons:
    - name: "Twitter"
      url: https://x.com/fthdgn_x
    - name: "YouTube"
      url: https://www.youtube.com/@fthdgn_yt
    - name: "LinkedIn"
      url: https://www.linkedin.com/in/fthdgn-li/
    - name: "Github"
      url: https://github.com/fthdgn-gh
    - name: "Mail"
      url: mailto:fth.dgn@outlook.com
  cover:
    linkFullImages: true